name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Save Docker images
        run: |
          docker save resource_server > resource_server.tar
          docker save authorization_server > authorization_server.tar
          docker save client > client.tar

      - name: Upload Docker images
        uses: actions/upload-artifact@v3
        with:
          name: resource_server
          path: resource_server.tar

      - name: Upload Docker images
        uses: actions/upload-artifact@v3
        with:
          name: authorization_server
          path: authorization_server.tar

      - name: Upload Docker images
        uses: actions/upload-artifact@v3
        with:
          name: client
          path: client.tar